{
	"id": "CVE-2017-7233",
	"vulnerabilities": [
		{
			"id": "CVE-2017-7233",
			"description": "Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely ``django.utils.http.is_safe_url()``) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.",
			"severity": [
				{
					"type": "cvss_v30",
					"source": "security.alpinelinux.org",
					"cvss_v30": {
						"vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"base_score": 6.1,
						"base_severity": "MEDIUM",
						"temporal_score": 6.1,
						"temporal_severity": "MEDIUM",
						"environmental_score": 6.1,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2017-7233"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.debian.org/security/2017/dsa-3835"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.securityfocus.com/bid/97406"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2017:1445"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2017:1451"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2017:1462"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2017:1470"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2017:1596"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2017:3093"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://access.redhat.com/errata/RHSA-2018:2927"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.djangoproject.com/weblog/2017/apr/04/security-releases/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://www.securitytracker.com/id/1038177"
				}
			],
			"published": "2017-04-04T17:59:00Z",
			"modified": "2023-11-29T06:20:42.895529Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.2",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.8.18-r0"
					}
				],
				"fixed": [
					"1.8.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.3",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.8.18-r0"
					}
				],
				"fixed": [
					"1.8.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.4",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.8.18-r0"
					}
				],
				"fixed": [
					"1.8.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.5",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.8.18-r0"
					}
				],
				"fixed": [
					"1.8.18-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.6",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.7",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.8",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.9",
			"vulnerable": true,
			"package": {
				"name": "py-django"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "1.10.7-r0"
					}
				],
				"fixed": [
					"1.10.7-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
