{
	"id": "CVE-2020-15890",
	"vulnerabilities": [
		{
			"id": "CVE-2020-15890",
			"description": "LuaJit through 2.1.0-beta3 has an out-of-bounds read because __gc handler frame traversal is mishandled.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"base_score": 7.5,
						"base_severity": "HIGH",
						"temporal_score": 7.5,
						"temporal_severity": "HIGH",
						"environmental_score": 7.5,
						"environmental_severity": "HIGH"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-15890"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00026.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/LuaJIT/LuaJIT/issues/601"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://usn.ubuntu.com/4501-1/"
				}
			],
			"published": "2020-07-21T22:15:12Z",
			"modified": "2024-06-30T12:57:15.505871Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.13",
			"vulnerable": true,
			"package": {
				"name": "luajit"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "2.2.0-r3"
					}
				],
				"fixed": [
					"2.2.0-r3"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
