{
	"id": "CVE-2020-1747",
	"vulnerabilities": [
		{
			"id": "CVE-2020-1747",
			"description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
						"base_score": 9.8,
						"base_severity": "CRITICAL",
						"temporal_score": 9.8,
						"temporal_severity": "CRITICAL",
						"environmental_score": 9.8,
						"environmental_severity": "CRITICAL"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-1747"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/yaml/pyyaml/pull/386"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.oracle.com/security-alerts/cpujul2022.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/"
				}
			],
			"published": "2020-03-24T15:15:12Z",
			"modified": "2024-05-22T17:20:50.665041Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.11",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.12",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.13",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.14",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.16",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.17",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.18",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.19",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.20",
			"vulnerable": true,
			"package": {
				"name": "py3-yaml"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "5.3.1-r0"
					}
				],
				"fixed": [
					"5.3.1-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
