{
	"id": "CVE-2021-28676",
	"vulnerabilities": [
		{
			"id": "CVE-2021-28676",
			"description": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"base_score": 7.5,
						"base_severity": "HIGH",
						"temporal_score": 7.5,
						"temporal_severity": "HIGH",
						"environmental_score": 7.5,
						"environmental_severity": "HIGH"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2021-28676"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202107-33"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/python-pillow/Pillow/commit/bb6c11fb889e6c11b0ee122b828132ee763b5856"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://github.com/python-pillow/Pillow/pull/5377"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
				}
			],
			"published": "2021-06-02T16:15:08Z",
			"modified": "2024-05-14T08:32:50.123193Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.14",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.2.0-r0"
					}
				],
				"fixed": [
					"8.2.0-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "py3-pillow"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "8.2.0-r0"
					}
				],
				"fixed": [
					"8.2.0-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
