{
	"id": "CVE-2021-3426",
	"vulnerabilities": [
		{
			"id": "CVE-2021-3426",
			"description": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "security.alpinelinux.org",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
						"base_score": 5.7,
						"base_severity": "MEDIUM",
						"temporal_score": 5.7,
						"temporal_severity": "MEDIUM",
						"environmental_score": 5.7,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2021-3426"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.gentoo.org/glsa/202104-04"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.netapp.com/advisory/ntap-20210629-0003/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2021/04/msg00005.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1935913"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.oracle.com/security-alerts/cpujan2022.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00039.html"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/25HVHLBGO2KNPXJ3G426QEYSSCECJDU5/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BF2K7HEWADHN6P52R3QLIOX27U3DJ4HI/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/DQYPUKLLBOZMKFPO7RD7CENTXHUUEUV7/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LM5V4VPLBHBEASSAROYPSHXGXGGPHNOE/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6VXJZSZ6N64AILJX4CTMACYGQGHHD5C/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QNGAFMPIYIVJ47FCF2NK2PIX22HUG35B/"
				},
				{
					"source": "security.alpinelinux.org",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VPX7Y5GQDNB4FJTREWONGC4ZSVH7TGHF/"
				}
			],
			"published": "2021-05-20T13:15:07Z",
			"modified": "2024-05-14T08:55:44.411782Z"
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.15",
			"vulnerable": true,
			"package": {
				"name": "python3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "3.9.4-r0"
					}
				],
				"fixed": [
					"3.9.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.16",
			"vulnerable": true,
			"package": {
				"name": "python3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "3.9.4-r0"
					}
				],
				"fixed": [
					"3.9.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.17",
			"vulnerable": true,
			"package": {
				"name": "python3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "3.9.4-r0"
					}
				],
				"fixed": [
					"3.9.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.18",
			"vulnerable": true,
			"package": {
				"name": "python3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "3.9.4-r0"
					}
				],
				"fixed": [
					"3.9.4-r0"
				]
			}
		},
		{
			"ecosystem": "alpine:3.19",
			"vulnerable": true,
			"package": {
				"name": "python3"
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "3.9.4-r0"
					}
				],
				"fixed": [
					"3.9.4-r0"
				]
			}
		}
	],
	"data_source": "alpine-osv"
}
